### ISSUE TITLE
Users will be able to see all sponsors on a sponsors page

### ISSUE THREAD

**Issue by iambriansreed** [RevolutionConf/Website#1]

**Comment by iambriansreed** [comment]
@erikpmp @1kevgriff @lynnaloo When does this need to be on the site?

**Comment by erikpmp** [comment]
ASAP

**Comment by erikpmp** [comment]
A dedicated sponsors page is not needed as long as the home page shows the sponsor's name, logo and a URL to their site (opens in a new tab). So I'm going to close this.
