### ISSUE TITLE
Need bio/photo for "About" page

### ISSUE THREAD

**Issue by lynnaloo** [RevolutionConf/Website#10]
We need each organizer/advisory board member to provide a short description and photo for the website.

**Comment by erikpmp** [comment]
Here's mine. I'm sure the short bio will be more than enough.

![erik headshot 2](https://cloud.githubusercontent.com/assets/1593872/12654317/599913e0-c5c1-11e5-898b-4339e37f13c3.jpg)

====

**Short Bio**

Erik is President of 80/20; a Norfolk software agency that provides application and consulting solutions to businesses. 

**Long Bio**

Erik Olson is a programmer, business consultant, and the President of 80/20 (http://8020.co), a software applications and consulting company in Norfolk, VA. Erik has over 15 years of professional experience in software development and managing software projects ranging from multi-year, multi-million dollar DoD enterprise initiatives, to line-of-business applications for small and mid-sized businesses. 

Erik holds a Bachelor's and MBA, both from Virginia Tech, is a Professional Project Manager (PMP), serves as the Past President of PMI Hampton Roads, is a mentor and investor at Hatch Norfolk, and is a software columnist for Inside Business.

**Comment by seanmerron** [comment]
![12-11-2015 bw](https://cloud.githubusercontent.com/assets/3949440/12659545/4f962394-c5dd-11e5-9448-1933cd66df33.jpg)

**Short**
Sean is a senior software developer and entrepreneur that enjoys tacos, hockey and tech meetups. 

**Long**
Sean Merron is a father, husband, geek, entrepreneur, surfer, hockey player, Philadelphia sports fan, Irishman, health goer, systems engineer / software architect / web developer / [fill in the blank here for whatever you call that IT person who can automate any process to save your company money]. Sean has a vast technical background but primarily focuses in the Microsoft .NET Framework providing web-based solutions.

**Comment by lynnaloo** [comment]
<img width="246" alt="bio-pic" src="https://cloud.githubusercontent.com/assets/1610195/12680121/22b7a34a-c676-11e5-9b34-fce7a1527398.png">

Linda is a software developer and robot evangelist at Emerging Technology advisors. She's also a co-organizer of Norfolk.js, International NodeBots Day, and several local technical classes and workshops.

**Comment by 1kevgriff** [comment]
![kevin_griffin_headshot](https://cloud.githubusercontent.com/assets/708542/12680375/80244708-c677-11e5-823e-58707c29ab64.jpg)

Kevin Griffin is an author, teacher, mentor, and consultant focusing in software development. He is the author of the Twilio Blueprint (http://twilioblueprint.com). As an independent consultant, Kevin specializes in helping businesses push their technology stacks into the 21st century. You can often find Kevin speaking at conferences and user groups across the country or blogging at http://kevgriffin.com.

**Comment by aproaps** [comment]
![headshot main](https://cloud.githubusercontent.com/assets/16326831/12680406/ac075982-c677-11e5-99ff-bec95d8d90d3.jpg)

Alex is a design psychology consultant. She is passionate about improving human-technology interaction through human-centered design, scientific research, and multi-disciplinary collaboration. Find her on Twitter: @alexproaps.

**Comment by JeffMatson** [comment]
![c1_7587_r_x](https://cloud.githubusercontent.com/assets/6805601/12757541/783392d8-c9a6-11e5-9794-1cd11b5b44dd.jpg)

Jeff is a developer, documentation writer, speaker, and WordPress contributor.  He currently works for Rocketgenius, the creator of the Gravity Forms plugin for WordPress.  Jeff also co-organizes the 757 WordPress Developers meetup group.  In his off time, he's usually messing around with classic arcade machines or other various hardware.  You can find Jeff on Twitter at @TheJeffMatson.

**Comment by erikpmp** [comment]
All contributors populated in the back-end. But I can't upload photos due to bug #24

**Comment by erikpmp** [comment]
All organizer, adviser, and volunteer data and pics populated in WP. Closing...
