### ISSUE TITLE
Need description for "About" page

### ISSUE THREAD

**Issue by lynnaloo** [RevolutionConf/Website#11]
We need a couple paragraphs for what this conference is about. @1kevgriff I assigned you because I think we may already have this from our emails.

**Comment by erikpmp** [comment]
Be sure to include that we're a 501c3 non-profit organization

**Comment by erikpmp** [comment]
I can take this.

**Comment by erikpmp** [comment]
Moved to https://github.com/RevolutionConf/Organization/issues/93. Closing this issue in this repo.
