### ISSUE TITLE
Landing page: change speakers submission due date

### ISSUE THREAD

**Issue by erikpmp** [RevolutionConf/Website#12]
Change from...

DEADLINE FOR SUBMISSIONS IS ON 2.29.16

To...

DEADLINE FOR SUBMISSIONS IS ON 2.14.16

**Comment by iambriansreed** [comment]
Trying to get http://2016.revolutionconf.com/ out in the world don't want to keep updating the old landing page.

**Comment by erikpmp** [comment]
if we can get the new site out in a day or two, great. otherwise we're causing some confusion.
