### ISSUE TITLE
2016: Tag line change

### ISSUE THREAD

**Issue by 1kevgriff** [RevolutionConf/Website#14]
I really think "The First Annual Technology Conference..." reads poorly.

Open to suggestions.

"Join the Revolution: Uniting software professionals from all walks of life."

@lynnaloo @erikpmp

**Comment by erikpmp** [comment]
+1

**Comment by lynnaloo** [comment]
I'm late getting to this issue, but I'd like to remove "all walks of life" just because it can read as speaking to social status instead of "all languages" or "all development environments" as we're trying to say
