### ISSUE TITLE
Change number of speakers to number of sessions

### ISSUE THREAD

**Issue by erikpmp** [RevolutionConf/Website#17]
25 speakers is an estimate. The more important number is the number sessions.

Change 25 speakers to "28 sessions"

![screenshot 2016-02-01 at 10 30 12 am](https://cloud.githubusercontent.com/assets/1593872/12721668/e6c6aa10-c8ce-11e5-8012-85613911984b.png)

**Comment by iambriansreed** [comment]
You had in the spreadsheet estimate 3 speakers with two talks.

**Comment by 1kevgriff** [comment]
We're reserving the right to not do that.  Better to promote the sessions themselves, and later change to reflect speakers.

**Comment by iambriansreed** [comment]
Yeah that makes more sense, focused on the number not word ... speakers/sessions.
