### ISSUE TITLE
Users will be able to see an abbreviated list of sponsors on the home page

### ISSUE THREAD

**Issue by iambriansreed** [RevolutionConf/Website#2]

**Comment by iambriansreed** [comment]
@erikpmp @1kevgriff @lynnaloo  When does this need to be on the site?

**Comment by erikpmp** [comment]
ASAP. Sponsors have paid and we've sold putting their info on our site.

**Comment by erikpmp** [comment]
@iambriansreed Please add this to your near-term TODO. We have received several checks from sponsors and need to be able to provide the value they've purchased.

**Comment by erikpmp** [comment]
RE: #1 A dedicated sponsors page is not needed as long as the home page shows the sponsor's name, logo and a URL to their site (opens in a new tab).
