### ISSUE TITLE
Correct discounts show on ribbons

### ISSUE THREAD

**Issue by erikpmp** [RevolutionConf/Website#20]
- [ ] Student discount is 50%. 
- [ ] Early Bird discount is 75%

This is based on a normal ticket price of $100.

![screenshot 2016-02-01 at 10 34 13 am](https://cloud.githubusercontent.com/assets/1593872/12721767/5fd3863a-c8cf-11e5-9fa9-8c0a05c3d015.png)

**Comment by iambriansreed** [comment]
50% off , 25% off respectively

**Comment by erikpmp** [comment]
ugh, yah...25% discount for early bird. thanks.
