### ISSUE TITLE
Get rid of the #. Use html5Mode

### ISSUE THREAD

**Issue by erikpmp** [RevolutionConf/Website#23]
`revolutionconf.com` redirects you to `http://revolutionconf.com/#/home`.

This article shows how to set html5mode, remove the #, and how to get "pretty" URLs.
https://scotch.io/quick-tips/pretty-urls-in-angularjs-removing-the-hashtag#$locationprovider-and-html5mode

**Comment by iambriansreed** [comment]
Been there. Done html5mode before.
Without doing a 404.html hack you can't do html5mode on Github pages.
