### ISSUE TITLE
Error uploading contributor photo

### ISSUE THREAD

**Issue by erikpmp** [RevolutionConf/Website#24]
I tried to upload the image for Sean Merron, below, and received this error.

===

![screen shot 2016-02-10 at 11 08 50 am](https://cloud.githubusercontent.com/assets/1593872/12953056/dc12db06-cfe6-11e5-82d7-0c23b0cc0985.png)

===

![4f962394-c5dd-11e5-9448-1933cd66df33](https://cloud.githubusercontent.com/assets/1593872/12953037/cccfea08-cfe6-11e5-91d3-4cc1479e1f6f.jpg)

**Comment by iambriansreed** [comment]
I really want to use AWS to hold the media and not use the Wordpress server. Any body have a AWS account we can use for RevolutionConf?

**Comment by iambriansreed** [comment]
Fixed. Review and close please. @erikpmp

**Comment by erikpmp** [comment]
Fixed!
