### ISSUE TITLE
Contributors - add company fields

### ISSUE THREAD

**Issue by erikpmp** [RevolutionConf/Website#25]
Goal - when displaying a contributor I want the title to show like this...

CEO, [80|20](http://8020.co)

If that means adding a company name and company URL field to the contributors, that's cool. if you want to normalize into a new list, that's fine too.

**Comment by erikpmp** [comment]
Although we already have Business Website, so we just need Business Name.

**Comment by iambriansreed** [comment]
Business Name = Title

**Comment by iambriansreed** [comment]
Instead of linking just the name of the company white not link the whole block?

**Comment by erikpmp** [comment]
So Title for me would be what? "CEO, 80|20". It'd be clean and better for SEO to have just the company name link. But if it's too time consuming, that's fine.

**Comment by iambriansreed** [comment]
Sorry thought we were talking about sponsors.

**Comment by iambriansreed** [comment]
Fixed...
![image](https://cloud.githubusercontent.com/assets/2301464/12967023/f3ac1cb0-d030-11e5-8511-5cd275f053ac.png)

**Comment by iambriansreed** [comment]
@erikpmp Review solution and close please.

**Comment by erikpmp** [comment]
Good to go!
