### ISSUE TITLE
Tickets in WP admin not affecting tickets shown on public site

### ISSUE THREAD

**Issue by erikpmp** [RevolutionConf/Website#28]
Changes I made in WP Admin:
* Changed Early Bird to Wave 1
* Add Wave 2 and Wave 3 tickets

These changes had no effect on what is displayed on revolutionconf.com.

Additionally, the following changes need to be made to the existing tickets section:
* Student ticket - change to "60% off Wave 2 pricing"
* Early bird
  * Change "Early Bird" to "Wave 1"
  * Change to "40% off Wave 2 pricing"
  * Change 3/1 to 2/22

**Comment by iambriansreed** [comment]
Not a bug just not completed yet.

**Comment by erikpmp** [comment]
done
