### ISSUE TITLE
About / Learn More - confusing navigation

### ISSUE THREAD

**Issue by erikpmp** [RevolutionConf/Website#34]
When you click on the Learn More button in About Us, the whole page is taken over by the list of organizers, advisers, and volunteers. The rest of the content (ex: speakers, sessions) is gone. That caused me some confusion about how to get out of that view. 

Maybe:
* Keep the rest of the content
* Add a Home menu item - which is what I looked for when I ended up looking at all of the team.

**Comment by iambriansreed** [comment]
Star?

**Comment by erikpmp** [comment]
What do you mean @iambriansreed ?

**Comment by iambriansreed** [comment]
>>>The rest of the content (ex: speakers, sessions) is gone. That caused me some confusion about how to get out of that view. 

The top navigation bar is clear enough I think.
Perhaps we need a change in style from the about section to the about page itself as they look pretty close before the advisors.

I did add the Star which takes you to home intro but really all the items in the top nav take you home.

**Comment by erikpmp** [comment]
the star is fine for now. not a priority as long as the star stays (it's gone on STG)
