### ISSUE TITLE
Tickets section changes

### ISSUE THREAD

**Issue by erikpmp** [RevolutionConf/Website#37]
* [ ] Remove "(0% OFF ORIGINAL PRICE)". Only show the "discount" if it's > 
* [ ] Would be better to first show the wave number (ex: Wave 2), then the ticket price. Ex: `Wave 2, $125`
* [x] Need to continue to show student pricing (it's still active)
* [x] Continue to show Wave 1 pricing. Even though it's expired, it shows ppl that they're late to the game, we sold out (that's good PR), and they should buy earlier next year.

**Comment by erikpmp** [comment]
Slight change please. Change "(X% OFF ORIGINAL PRICE)" to "(60% OFF CURRENT PRICE)" - change original to current. We will change the percentage as the waves change.

**Comment by iambriansreed** [comment]
This will need some coordination.

**Comment by erikpmp** [comment]
it's taken care of

**Comment by iambriansreed** [comment]
@erikpmp Where does this stand. Does any further action need to happen on my end?

**Comment by erikpmp** [comment]
No. The parts that needed to change have been changed and the rest can be ignored.
