### ISSUE TITLE
Hotel/Travel Logistics

### ISSUE THREAD

**Issue by 1kevgriff** [RevolutionConf/Website#41]
VBRH Phone number + "ask for RevolutionConf" rate!  $109/night + taxes and fees

- 20 minutes from Norfolk International Airport (ORF)
- 20 minutes from Norfolk Amtrak (NFK)
- 40 minutes from Newport News Amtrak (NPN)

We have Uber and Lyft, and App-A-Cab.

**Comment by iambriansreed** [comment]
@1kevgriff How do you see the UI presenting this information?

**Comment by 1kevgriff** [comment]
Might be a good question for @aureately?  Maybe add another section within "Location"?  Doesn't have to be too fancy.  

Me spitballing:

> Virginia Beach Resort Hotel
> 2800 Shore Drive 
> Virginia Beach, VA 23451
> [View Map]  [Free Parking]
> 
> **Discounted Rates**
> Call the Virginia Beach Resort Hotel at 1-800-468-2722 and ask them for the "RevolutionConf" rate.  $109/night plus taxes and fees.
> 
> **Out of town?**
> If you are flying in for the conference, your best bet is Norfolk International (ORF).  It's only 20 minutes away! 
> 
> If you are taking the train, Amtrak has stations in Norfolk (NFK) or Newport News (NPN).
> 
> If you don't want to rent a car, Uber and Lyft both fully service the area.  App-A-Cab is also available.
> 

ping @lynnaloo @erikpmp for opinions.

**Comment by 1kevgriff** [comment]
@iambriansreed Bump this.  We're starting to get questions.  
 
![discount_r2](https://cloud.githubusercontent.com/assets/708542/13581831/e1be009a-e476-11e5-851c-f948ccf75a51.png)

**Comment by erikpmp** [comment]
just got an email from someone asking about this, so people need this info @iambriansreed
