### ISSUE TITLE
Sessions - separate keynote from other talks

### ISSUE THREAD

**Issue by erikpmp** [RevolutionConf/Website#42]
Keynote should be it's own section, before other talks, and include the keynote speaker info.

**Comment by iambriansreed** [comment]
Would the Keynote session title be there? Has the Keynote session been created yet?

**Comment by erikpmp** [comment]
>Would the Keynote session title be there? 

Yes

>Has the Keynote session been created yet?

Yes. But he wasn't showing at all because only contributors that were speakers were showing. As a temporary measure, I changed Matt's type from keynote to speaker so he'd at least show up on the site. once the code shows the keynote then we'll change his type back to keynote.

**Comment by erikpmp** [comment]
done
