### ISSUE TITLE
lag on the initial load

### ISSUE THREAD

**Issue by erikpmp** [RevolutionConf/Website#44]
Per @1kevgriff:

>repeats over and over and over again
full load was about 8 seconds
couple angular errors on the console too
>
>![pasted image at 2016_02_21 11_30 pm](https://cloud.githubusercontent.com/assets/1593872/13218103/387db3b4-d935-11e5-9661-896c39a2c36c.png)

**Comment by erikpmp** [comment]
it's back...

![screen shot 2016-02-23 at 3 34 55 pm](https://cloud.githubusercontent.com/assets/1593872/13266247/18dad10c-da45-11e5-86dd-2927e744335b.png)

**Comment by iambriansreed** [comment]
https://github.com/RevolutionConf/Website-App-2016/pull/13

Good to go

**Comment by erikpmp** [comment]
Fixed
