### ISSUE TITLE
Reposition the map

### ISSUE THREAD

**Issue by erikpmp** [RevolutionConf/Website#48]
Vertically center the venue within the area set aside for the map.

![screenshot 2016-02-23 at 12 16 35 pm](https://cloud.githubusercontent.com/assets/1593872/13260831/5aaccbc2-da2b-11e5-94d8-bd30177be5bb.png)

**Comment by iambriansreed** [comment]
Please add the resolution/browser that made this issue occur. I need to replicate before I can fix.

**Comment by erikpmp** [comment]
It was Chrome on the Chromebox in the conference room. 

Same thing is happening on my 27" thunderbolt monitor, actually worse...you can't see the location at all.  Safari on the left; Chrome on the right.

![screen shot 2016-02-24 at 9 03 30 am](https://cloud.githubusercontent.com/assets/1593872/13287571/b3a229e8-dad5-11e5-9224-04be15611f64.png)

 As the page grows in height, the location marker moves up and out of view behind the above section.

short view...

![screen shot 2016-02-24 at 9 05 30 am](https://cloud.githubusercontent.com/assets/1593872/13287603/d720023c-dad5-11e5-88a7-9bd8cc4e6791.png)

tall view...

![screen shot 2016-02-24 at 9 05 37 am](https://cloud.githubusercontent.com/assets/1593872/13287610/dfead978-dad5-11e5-90b7-503afac64307.png)

**Comment by iambriansreed** [comment]
Thanks for the breakdown.

**Comment by erikpmp** [comment]
Much better. push it.

**Comment by erikpmp** [comment]
looks good on prod
