### ISSUE TITLE
Link to conference-specific CoC

### ISSUE THREAD

**Issue by lynnaloo** [RevolutionConf/Website#53]
We need a slightly more specific Code of Conduct that has the email(s) for people to use if they need to report a violation. I'll provide the content.

**Comment by lynnaloo** [comment]
I created a CoC here with RevolutionConf-specific information and contact information for @lynnaloo, @erikpmp, and @1kevgriff: https://github.com/RevolutionConf/Organization/blob/master/CODE-OF-CONDUCT.md.

**Comment by iambriansreed** [comment]
@lynnaloo Should I add this as a page to the site, or be cool and link to the readme?

**Comment by lynnaloo** [comment]
I think a page on the site would be better

**Comment by iambriansreed** [comment]
You got it.

**Comment by lynnaloo** [comment]
:heart_eyes:

**Comment by iambriansreed** [comment]
@lynnaloo Apologies on the response time.
http://revolutionconf.com/#/code-of-conduct

**Comment by lynnaloo** [comment]
Awesome! Thanks @iambriansreed

**Comment by erikpmp** [comment]
I'm pretty sure this is done, so I'm closing.
