### ISSUE TITLE
Add Student Scholarship

### ISSUE THREAD

**Issue by erikpmp** [RevolutionConf/Website#54]
Somewhere, maybe even in the tickets section, we need to add verbiage and a link/button to the 5 student tickets scholarship. Ideas welcomed. Scholarship expires at the end of 4/15/2016.

http://goo.gl/forms/fQdtA8BSoi

**Comment by iambriansreed** [comment]
Def need more info here.  This seems like an section in the tickets area.

**Comment by erikpmp** [comment]
@aureately, can you help us figure out the best location to place info on the 5 ticket student scholarship? Thanks.

**Comment by erikpmp** [comment]
Will be addressed when #57 is completed. Closing...
