### ISSUE TITLE
Order sponsor logos

### ISSUE THREAD

**Issue by erikpmp** [RevolutionConf/Website#56]
Show logos in this order:

1. Premier
2. Lunch
3. Happy Hour
4. VIP
5. Large Room
6. Medium Room
7. Logo Only

**Background**

A logo only sponsor is showing up at the same "position" as a premier who is paying > 10X more.

**Comment by iambriansreed** [comment]
![image](https://cloud.githubusercontent.com/assets/2301464/13973362/6f87216a-f078-11e5-886f-85bc9752d9e8.png)

**Comment by erikpmp** [comment]
@iambriansreed what's the URL and credentials (same as prod?) to log into STG?

**Comment by erikpmp** [comment]
I logged into PROD and see the reorder menu item, used it and it worked. So I think the "test staging" label on this issue was wrong or old. Works on PROD...closing.
