### ISSUE TITLE
On mobile, tickets not fitting on the screen

### ISSUE THREAD

**Issue by erikpmp** [RevolutionConf/Website#59]
As viewed on my iPhone 5S...

![img_5778](https://cloud.githubusercontent.com/assets/1593872/14936533/593aa9d2-0ebd-11e6-8da2-2fb57a47a2c3.PNG)

===

![img_5779](https://cloud.githubusercontent.com/assets/1593872/14936532/57088ac6-0ebd-11e6-967d-1a16078fc7a7.PNG)

**Comment by iambriansreed** [comment]
It's the URL. Remove it as it doesn't work anymore anyways.

**Comment by erikpmp** [comment]
I still the problem on my iPhone 5S in Chrome and Safari, even after I refresh several times. In Chrome desktop I do not see it in phone/responsive view, but do in phone/iphone 5 view (see below).

![screen shot 2016-05-02 at 11 42 45 am](https://cloud.githubusercontent.com/assets/1593872/14958918/0883ad32-105b-11e6-8006-57c7129be41b.png)

**Comment by erikpmp** [comment]
Looks correct in Chrome desktop iPhone 5 emulator. But it still looks the same on my iPhone 5S in Chrome and Safari, even after manually refreshing in both browsers. 

@lynnaloo and @1kevgriff on your iPhones do the wells within the ticket section render off the right of the screen like in the below screenshot from my phone?

![iphone](https://cloud.githubusercontent.com/assets/1593872/15074289/21887f42-136c-11e6-9b8a-5a96d26cad25.png)

**Comment by erikpmp** [comment]
@lynnaloo I'm assigning to you to review since I think @1kevgriff is traveling. If it works on your phone then we can chalk this up to something funky happening on my phone and you can close this issue.

**Comment by iambriansreed** [comment]
@erikpmp https://github.com/RevolutionConf/Website/issues/59#issuecomment-216261234

**Comment by erikpmp** [comment]
@iambriansreed I'm not sure what you're trying to communicate. Are you trying to indicate I'm doing something wrong?

I go to RevolutionConf.com and click Tickets in the menu. That takes me to http://revolutionconf.com/home#tickets.

**Comment by 1kevgriff** [comment]
I see same issue on iOS safari (not iOS chrome)

**Comment by erikpmp** [comment]
Still seeing the problem.




Erik
. . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . .
Erik Olson :: 80|20 :: Software Applications and Consulting
http://8020.co :: erik@8020.co :: 757.478.3083 :: @erikpmp

On May 11, 2016, at 8:11 PM, Brian Reed <notifications@github.com> wrote:

Closed #59.
