### ISSUE TITLE
On schedule, add " Room" after the room name

### ISSUE THREAD

**Issue by erikpmp** [RevolutionConf/Website#61]
It's not obvious what the room names by themselves mean. Ex: a marker with "Virginia"...they may think we're referencing the state of VA. Add " Room" after each room name on the schedule.

![screenshot 2016-05-05 at 3 48 58 pm](https://cloud.githubusercontent.com/assets/1593872/15055213/5d53b7e6-12d9-11e6-9699-000abd58050f.png)

**Comment by iambriansreed** [comment]
Content Change

**Comment by erikpmp** [comment]
I tried, but something is not right.

* In WP Admin I went to Custom Fields >> Session Details >> Room and edited the room names. Ex: I changed "Chesapeake A & B" to "Chesapeake A & B Room"
* I published the Sessions API
* I refreshed rc.com
* For the session "A Brief History of Cryptography", the room is "Chesapeake Room A & B". That room name does not match the old or new room name (notice the position of "Room")
* I then went to edit the session in WP Admin and noticed the room for the session is "Virginia Room"

So the room names between the Room names (in custom fields), edit session screen, and the front end are not matching. 

Am I doing something wrong?

===

![screen shot 2016-05-06 at 10 21 42 am](https://cloud.githubusercontent.com/assets/1593872/15079469/b53dc3e0-1386-11e6-99d8-6efa4cd85242.png)

===

![screen shot 2016-05-06 at 10 22 58 am](https://cloud.githubusercontent.com/assets/1593872/15079477/bdbc2c46-1386-11e6-8738-c7c477b43368.png)

===

![screen shot 2016-05-06 at 10 23 32 am](https://cloud.githubusercontent.com/assets/1593872/15079482/c338d516-1386-11e6-9f72-2c0e583a7c5b.png)

===

**Comment by iambriansreed** [comment]
This is fixed but the bug migrated to the schedule Dropdown. Fixing now.
